[env]
PYTHONPATH = "./src"

[tools]
python = "3.11"

[settings]
python.uv_venv_auto = true

[tasks.start]
description = "Run main.py"
run = """
mise use python@3.11
python main.py
"""
[tasks."setup:requirements"]
description = "Set up the project environment and dependencies"
run = """
mise use python@3.11
pip install -r requirements.txt
"""

[tasks."setup:aisafetylab"]
description = "Install AISafetyLab dependency in deps directory" # @TODO make this a proper library/module and axe this task
run = """
mkdir -p deps
cd deps
git clone git@github.com:thu-coai/AISafetyLab.git
cd AISafetyLab
pip install -e .
"""

[tasks.install]
run = """
mise run setup:aisafetylab
mise run setup:requirements
"""

[tasks.dev]
description = "Start development environment"
run = "mise use python@3.11" 
